# msa-notice Service
apiVersion: v1
kind: Service
metadata:
  name: notice-service
spec:
  selector:
    app: msa-notice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP